export const EMULATOR_DATA_PARTITION_SIZE_PATTERN = /^([1-9][0-9]*)(G|GB)$/;
export const EMULATOR_BOOT_TIMEOUT_MS = 180_000;
export const ADB_REGISTRATION_TIMEOUT_MS = 60_000;
export const BOOT_POLL_INTERVAL_MS = 2_000;
