export const ERROR_CODES = {
  ANDROID_CATALOG_QUERY_FAILED: "ANDROID_CATALOG_QUERY_FAILED",
  ADB_QUERY_FAILED: "ADB_QUERY_FAILED",
  ANDROID_AVD_CREATE_FAILED: "ANDROID_AVD_CREATE_FAILED",
  ANDROID_SDK_TOOL_MISSING: "ANDROID_SDK_TOOL_MISSING",
  ANDROID_SYSTEM_IMAGE_INSTALL_FAILED: "ANDROID_SYSTEM_IMAGE_INSTALL_FAILED",
  EMULATOR_ALREADY_RUNNING: "EMULATOR_ALREADY_RUNNING",
  EMULATOR_BOOT_TIMEOUT: "EMULATOR_BOOT_TIMEOUT",
  EMULATOR_DELETE_FAILED: "EMULATOR_DELETE_FAILED",
  EMULATOR_NOT_FOUND: "EMULATOR_NOT_FOUND",
  EMULATOR_NOT_RUNNING: "EMULATOR_NOT_RUNNING",
  EMULATOR_START_FAILED: "EMULATOR_START_FAILED",
  EMULATOR_STOP_FAILED: "EMULATOR_STOP_FAILED",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  ANDROID_AVD_ALREADY_EXISTS: "ANDROID_AVD_ALREADY_EXISTS",
} as const;

export interface EmulatorError {
  code: (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
  message: string;
  details?: Record<string, unknown>;
}
